title: My Awesome Website
description: A site built with Jekyll on GitHub Pages
theme: jekyll-theme-cayman

# Optional settings
author: lismarta88-source
email: your-email@example.com
baseurl: "" # Leave empty for username. github.io sites
url: "https://lismarta88-source.github.io"
